url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "MLMPS # the name of your site, e.g. ACME Corp.
description: "Working group on machine learning methods for physical systems"
